### ISSUE TITLE
Tray icons suggestion

### ISSUE THREAD

**Issue by guoyunhe** [caybro/plasma-pk-updates#2]
Currently, here are only 3 status of tray icon in KDE 5.

![image](https://cloud.githubusercontent.com/assets/5836790/11165171/95bf466e-8b10-11e5-885d-2a8b8f17dfc3.png)

When there is optional updates or no updates, it always show the green icon. Sometimes users do not notice here are updates. The green check gives people a feeling of "everything is okay, nothing to do".

And this green icon is very different from other tray icon. Maybe they are not icons for system tray.

![image](https://cloud.githubusercontent.com/assets/5836790/11165199/5f089fb6-8b11-11e5-8676-380bf356b930.png)

I made some new icons that might be helpful:

![image](https://cloud.githubusercontent.com/assets/5836790/11165421/dec44868-8b16-11e5-8162-118b1c22e3f5.png)

https://cloud.guoyunhe.me/index.php/s/7Sn7yQS1N7qJ4H7

Four status:
- no update
- low update (optional update, new feature update)
- medium update (bugfix update)
- high update (security update)

Size: 24px

Format: SVG

**Comment by grulja** [comment]
Hi,

thanks for your suggestions, we just moved plasma-pk-updates to a KDE git repository and we will continue the development there. I like your icons, they are definitely better than the security-foo icons we use right now, but to be able to use your icons you would need to contact KDE VDG group and include your icons with Plasma breeze theme, it's not a good idea shipping those icons together with plasma-pk-updates.

Thanks.

**Comment by guoyunhe** [comment]
Posted a new thread on KDE forum. Hope someone will accept it! https://forum.kde.org/viewtopic.php?f=285&t=129414

**Comment by Andreas-Kainz** [comment]
Hi

I like your idea too. I'm not sure about the icon names but if the devs want to use this icons it would be nice.

about the design we have guidelines for the color (https://github.com/NitruxSA/breeze-icon-theme/wiki/Icon-design-guidelines-in-Breeze#colors) so please use the colors from the guideline. About the sheeld I made an open sheeld for security low and an closed sheeld for security high. but we can use also the half closed sheeld. no problem.

we can add this new icons in breeze, breeze-dark and oxygen when the dev's support the new names. No problem.

**Comment by guoyunhe** [comment]
4 new icons for software update have been added to Breeze icons. You might consider to use it in plasma-pk-updates.

![1](https://cloud.githubusercontent.com/assets/5836790/11368548/07a7e952-92c3-11e5-9c3f-aba2300c932b.png)

**Comment by grulja** [comment]
Thanks, I'll update plasma-pk-updates accordingly. Btw. the git repository has moved under KDE so you can report bugs on bugs.kde.org.
